### ISSUE TITLE
Nice project ! Maybe i can help :)

### ISSUE THREAD

**Issue by F0x06** [revosw/learnwiremod#13]
Hi, i've seen your project searching for projects realted to wiremod, i'm really sad now due to the shutdown of wiremod.com, this project is a really great idea to help future players with wiremod ! If i have some time i'ill help you with some pull request, specifically with CPU & E2, and also general wiring.

i recently started to play Gmod again, i'm on various CPU projects ATM, 4000 hrs is not enough !

Keep going !

**Comment by revosw** [comment]
Heyheyyyyy!

I am thrilled that you've picked interest in the project, hit me up on discord: Revolution#7018

I've been procrastinating so bad on this project, it has come to a complete stall. It would be lovely if there were someone who could get a little fresh air on it ;)

**Comment by F0x06** [comment]
> Heyheyyyyy!
> 
> I am thrilled that you've picked interest in the project, hit me up on discord: Revolution#7018
> 
> I've been procrastinating so bad on this project, it has come to a complete stall. It would be lovely if there were someone who could get a little fresh air on it ;)

Hi ! :), I'll contact you on discord when i have a bit of time, it's important to keep WireMod alive since all help places are gone, for ex wiremod.com, and allow new players to learn some basics first instead of too complicated tutorials, this will discourage people otherwise... 

The most obscure part IMHO is the wire CPU, it need more "basic" tutorials to understand the bases, the best approach would be some really simple builds and more example-oriented courses.

F0x.

**Comment by revosw** [comment]
Hey, it went quiet. Hit me up anytime

**Comment by F0x06** [comment]
> Hey, it went quiet. Hit me up anytime

Hi! Lot of work these days, not enough time, soon I'll contact you :)
